---
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: yeti
    favicon: "images/favicon.ico"
    logo: "images/logo_height_45px.png"
    source_code: "https://github.com/ThinkR-open/thinkrdashboard"
params:
  title:
    label: Title of report
    value: ThinkR dashboard
    input: text
  dashboard_start: 
    label: Start date of report
    value: !r lubridate::today() - lubridate::ddays(90)
    input: date
  orgs:
    label: GitHub organizations
    value: ThinkR-open, statnmap, colinfay, VincentGuyader, Cervangirard, MargotBr, DianeBeldame
    input: text
  privacy:
    label: Repository Privacy
    value: PUBLIC
    choices: [PUBLIC, PRIVATE, BOTH]
title: "`r params$title`"	
---

```{r setup, include = FALSE}
# knitr::opts_chunk$set(eval = FALSE, cache = TRUE)

library(flexdashboard)
library(gh)
library(jsonlite)
library(lubridate)
library(forcats)
library(dplyr)
library(purrr)
library(tibble)
library(codetools) # there was a weird error on connect that needed this
library(DT)
# remotes::install_github("ThinkR-open/tidyversedashboard", ref = "zero-issues")
library(tidyversedashboard)
library(tidyr)
library(sparkline)
library(ggplot2)

gh_colors <- list(
  green = "#2cbe4e",
  red = "#CB2434",
  purple = "#6f42c1")
dashboard_start <- params$dashboard_start
dashboard_duration <- format(today() - dashboard_start, format = "%d")
orgs <- scan(text = params$orgs, what = "character", sep = ",", strip.white = TRUE, quiet = TRUE)
privacy <- normalize_privacy(params$privacy)

# plus1 emoji
p1 <- "\U0001f44d"
```

```{r remaining, message=FALSE}
#' Wait if required rate is above remaining one
#'
#' @param required Required amount of points you need for the next step
#' When using the built-in GITHUB_TOKEN in GitHub Actions, the rate limit is 1,000 requests per hour per repository
wait_for_rate <- function(required = 100) {
  
# Rate limit ----
ratelimit <- "query {
  viewer {
    login
  }
  rateLimit {
    limit
    cost
    remaining
    resetAt
  }
}"

rate_value <- gh::gh_gql(ratelimit)

message("Rate value:", rate_value)

  if (rate_value[[1]]$rateLimit$remaining < required) {
    # remaining seconds
    remaining <- round(as.numeric(as.duration(as_datetime(rate_value[[1]]$rateLimit$resetAt) - now())))
    
    message(paste("Let's wait a little", round(remaining/60), "minutes"))
    Sys.sleep(remaining)
  } else {
    message("Rate's good")
  }
}
```


```{r pr_stats, include=FALSE, message=FALSE}
options(repos = c(CRAN='https://cloud.r-project.org'))

wait_for_rate(280)

# Requires ~500 points for rate limitation
pr_data <- tryCatch(
  map_dfr(orgs, org_pr, privacy = privacy),
  error = function(e) message(e$content$errors))

if (!is.null(pr_data)) {
  prs <- pr_data %>% 
    filter(updated >= dashboard_start) %>%
    mutate(reviewer = map2(reviews, comments, function(reviews, comments) unique(c(reviews$reviewer, comments$commenter)))) %>%
    select(owner, repo, issue, author, created, updated, closed, reviewer) %>%
    unnest(cols = c(reviewer)) %>%
    filter(reviewer != author, reviewer != "codecov.io") %>%
    mutate(
      reviewer = github_user_home(reviewer),
      author = github_user_home(author),
      is_closed = !is.na(closed))

  pr_authors <- prs %>% group_by(author, is_closed) %>% select(-reviewer) %>% unique() %>% tally(sort = TRUE)
  pr_reviewers <- prs %>% group_by(reviewer, is_closed) %>% select(-author) %>% unique() %>% tally(sort = TRUE)
  pr_pairs <- prs %>% group_by(author, reviewer, is_closed) %>% tally(sort = TRUE)
} else {
  pr_authors <- NULL
  pr_reviewers <- NULL
  pr_pairs <- NULL
}

# Get remaining rate
wait_for_rate(1)
```

```{r repo_stats, include = FALSE, message=FALSE}
# Requires ~700 points for rate limitation
wait_for_rate(650)

repo_data <- map(orgs, org_data, privacy)

# Keep only repo where we are owners
repo_summary <- map_dfr(repo_data, "summary") %>% 
  distinct(owner, repo, .keep_all = TRUE) %>% 
  filter(tolower(owner) %in% tolower(orgs))
issues <- map_dfr(repo_data, "issues") %>% 
  distinct(owner, repo, issue, .keep_all = TRUE) %>% 
  filter(tolower(owner) %in% tolower(orgs))

# Get remaining
wait_for_rate(1)
```


`r dashboard_duration` issue progress
=====================================
```{r issue_progress, include = FALSE, message=FALSE}
# Requires ~20 points for rate limitation
wait_for_rate(15)

# Keep only repo where we are owners
issue_data_orig <- map_dfr(orgs, issue_progress, dashboard_start, privacy)

issue_data2 <- issue_data_orig %>% 
  distinct(owner, package, type, issue, .keep_all = TRUE) %>% 
  filter(tolower(owner) %in% tolower(orgs)) %>% 
  mutate(
    type = factor(levels = c("issue", "pull_request"),
      case_when(
        type == "Issue" ~ "issue",
        type == "PullRequest" ~ "pull_request")),

    status = factor(levels = c("opened", "closed", "merged"),
      case_when(
        merged >= dashboard_start ~ "merged",
        closed >= dashboard_start ~ "closed",
        opened >= dashboard_start ~ "opened",
        TRUE ~ NA_character_)),
    event = case_when(
      status == "merged" ~ merged,
      status == "closed" ~ closed,
      status == "opened" ~ opened)
  )

# Get remaining
wait_for_rate(1)
```

```{r}
totals <- issue_data2 %>% group_by(type, status) %>% tally() %>% mutate(n = if_else(status == "closed" | status == "merged", n * -1L, n)) %>% tidyr::drop_na()
```


Row
------------------------------

### `r dashboard_duration` Issues / pull requests opened
```{r}
valueBox(totals %>% filter(status == "opened") %>% pull("n") %>% sum(), icon = "fa-exclamation-circle", color = "success")
```

### `r dashboard_duration` Issues closed
```{r}
valueBox(totals %>% filter(type == "issue", status == "closed") %>% pull("n") %>% abs(), icon = "fa-times-circle", color = "danger")
```

### `r dashboard_duration` Pull requests merged / closed
```{r}
valueBox(totals %>% filter(type == "pull_request" & (status == "merged" | status == "closed")) %>% pull("n") %>% sum() %>% abs(), icon = "ion-merge", color = "info")
```

### `r dashboard_duration` issues/pull requests change
```{r}
change <- sum(totals$n)
valueBox(change, icon = "fa-exclamation-circle", color = if (change < 0) "success" else "danger")
```

### Total remaining open issues
```{r}
valueBox(nrow(issues), icon = "fa-exclamation-circle")
```

### Total remaining open pull requests
```{r}
if (!is.null(pr_data)) {
  pr_data %>% 
    filter(is.na(closed)) %>% 
    nrow() %>% 
    valueBox(., icon = "fa-exclamation-circle")
} else {
  valueBox("?", icon = "fa-exclamation-circle")
}
```

Row
-------------------------------------

### `r dashboard_duration` progess

```{r}
issue_progress_table <- issue_data2 %>%
  # Add maintiner to the table
    left_join(mutate(repo_summary, maintainer = desc_maintainer(description)) %>%
              select(repo, maintainer), by = c("package" = "repo")) %>%
  group_by(type, status) %>%
  arrange(event) %>%
  select(owner, package, issue, maintainer, event, status, type) %>%
  na.omit()

data_table(issue_progress_table)
```

> Issues with status modified (`r dashboard_start` - `r now()`).

### `r dashboard_duration`-day progress summary

```{r}
issue_data3 <- issue_data2 %>% 
  filter(!is.na(event)) %>% 
  select(event, owner, package, num = issue, type, status) %>% 
  mutate(
    date = as.Date(event),
    event = NULL,
    n = if_else(status %in% c("closed", "merged"), -1, 1)
  )

daily <- issue_data3 %>% 
  group_by(date, type, status) %>% 
  summarise(n = sum(n), .groups = "drop")

daily %>% 
  mutate(status = fct_relevel(status, "opened", "merged")) %>% 
  ggplot(aes(date, n, fill = type)) + 
  geom_col() +
  facet_grid(status ~ ., scales = "free_y", space = "free") +
  labs(
    title = "Daily changes in issues and PRs",
    x = NULL,
    y = NULL
  ) + 
  scale_y_continuous(breaks = scales::breaks_width(20), expand = c(0, 5)) +
  scale_fill_brewer(palette = "Set1", guide = NULL) + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b %d", date_minor_breaks = "1 week") +
  theme_bw() +
  theme(panel.grid.major.x = element_line(colour = "grey40"))
```

> `r dashboard_start` - `r now()`

Repository summary
=====================================



```{r repo_summary}
summary_table <- repo_summary %>%
  rename("package" = "repo") %>%
  mutate(
    weekly_downloads = num_downloads(.$package, "last-week"),
    maintainer = desc_maintainer(description),
    reverse_deps = reverse_dependencies(package),
    dev_deps = desc_dev_deps(description),
    github_status = github_status_badge(owner, package),
    cran_status = cran_status_badge(package),
    coverage_status = coverage_status_badge(owner, package, default = default_branch),
    topics = map_chr(topics, paste, collapse = ", "),
    activity = map2(owner, package, weekly_commits)) %>%
  select(owner, package, maintainer, topics, watchers, reverse_deps, weekly_downloads, open_issues, prs, p1, everything(), -description) %>%
  rename(!!p1 := p1)
```

```{r, eval=FALSE}
# Get codecov % coverage
library(httr2)
req <- request("https://codecov.io/api/gh/statnmap") %>% 
  req_headers("Authorization" = Sys.getenv("CODECOV_TOKEN"))
req

resp <- req_perform(req)
resp
resp %>%
  resp_body_json() %>% 
  dplyr::bind_rows()
```


```{r}
# A custom datatable with a sparkline column
dt <- sparkline_table(
  summary_table,
  sparkline_column = which(colnames(summary_table) == "activity"),
  colnames = c("52 week commit activity" = "activity"))
dt
```

Open issues
=====================================
```{r issue_summary}
substitute_emoji <- function(x) {
  m <- gregexpr(":[^[:space:]]+:", x)

  regmatches(x, m) <- lapply(regmatches(x, m), function(xx) map_chr(gsub(":", "", xx), purrr::possibly(emo::ji, "")))
  x
}

# linkify the titles, and replace emoji
issue_table <- issues %>% 
  mutate(
    title = glue::glue('<a rel="noopener" target="_blank" href="https://github.com/{owner}/{repo}/issues/{issue}">{title}</a>'),
    # Modify issue after title
    issue = glue::glue('<a rel="noopener" target="_blank" href="https://github.com/{owner}/{repo}/issues/{issue}">{issue}</a>'),
    # Modify repo after issue
    repo = glue::glue('<a rel="noopener" target="_blank" href="https://github.com/{owner}/{repo}">{repo}</a>'),
    labels = substitute_emoji(map_chr(labels, paste, collapse = ", "))) %>%
  rename(!!p1 := p1)

data_table(issue_table)
```

`r dashboard_duration` pull request summary
=====================================


### PR authors
```{r}
data_table(pr_authors)
```

### PR reviewers
```{r}
data_table(pr_reviewers)
```

### PR pairs
```{r}
data_table(pr_pairs)
```

```{r include=FALSE, message=FALSE}
# Get remaining
wait_for_rate(1)
```

