on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    # every day at midnight
    - cron: '00 00 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      REPO_NAME: "https://packagemanager.rstudio.com/all/__linux__/focal/latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ubuntu-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ubuntu-${{ hashFiles('.github/R-version') }}-1-
          
      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y libmagick++-dev
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')
          
      - name: Install packages
        run: |
          R -e 'install.packages("remotes")'
          R -e 'remotes::install_local(force = TRUE)'
          # R -e 'remotes::install_version("DT", version = "0.19")' # 0.20 fails with a max-height

      - name: Render Rmarkdown files
        run: |
          rmarkdown::render("thinkr_dashboard.Rmd", output_dir = "public")
        shell: Rscript {0}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
